Ext.define('zonblewou.store.mesStore.Nationalites', {
    extend: 'Ext.data.Store',

    alias: 'store.nationalites',
    //autoLoad: true,
    /*
    Uncomment to use a specific model class
    model: 'User',
    */

    //model: 'zonblewou.model.mesModeles.Nationalite',

    //Fields can also be declared without a model class:
    fields: ['nationalite', 'code'],

    //Uncomment to specify data inline
    data: [
        { nationalite: 'AFGHANISTAN', code: 'AFGHANISTAN' },
        { nationalite: 'AFRIQUE DU SUD', code: 'AFRIQUE DU SUD' },
        { nationalite: 'ALBANIE', code: 'ALBANIE' },
        { nationalite: 'ALGERIE', code: 'ALGERIE' },
        { nationalite: 'ALLEMAGNE', code: 'ALLEMAGNE' },
        { nationalite: 'ANDORRE', code: 'ANDORRE' },
        { nationalite: 'ANGOLA', code: 'ANGOLA' },
        { nationalite: 'ANGUILLA', code: 'ANGUILLA' },
        { nationalite: 'ANTIGUA-ET-BARBUDA', code: 'ANTIGUA-ET-BARBUDA' },
        { nationalite: 'ANTILLES NEERLANDAISES', code: '' },
        { nationalite: 'ARABIE SAOUDITE', code: '' },
        { nationalite: 'ARGENTINE', code: '' },
        { nationalite: 'ARMENIE', code: '' },
        { nationalite: 'ARUBA', code: '' },
        { nationalite: 'ASCENSION', code: '' },
        { nationalite: 'AUSTRALIE', code: '' },
        { nationalite: 'AUTRICHE', code: '' },
        { nationalite: 'AZERBAÏDJAN', code: '' },
        { nationalite: 'BAHAMAS', code: '' },
        { nationalite: 'BAHREÏN', code: '' },
        { nationalite: 'BANGLADESH', code: '' },
        { nationalite: 'BARBADE', code: '' },
        { nationalite: 'BELGIQUE', code: '' },
        { nationalite: 'BELIZE', code: '' },
        { nationalite: 'BENIN', code: '' },
        { nationalite: 'BERMUDES', code: '' },
        { nationalite: 'BHOUTAN', code: '' },
        { nationalite: 'BIELORUSSIE', code: '' },
        { nationalite: 'BIRMANIE', code: '' },
        { nationalite: 'BOLIVIE', code: '' },
        { nationalite: 'BOSNIE-HERZEGOVINE', code: '' },
        { nationalite: 'BOTSWANA', code: '' },
        { nationalite: 'BRESIL', code: '' },
        { nationalite: 'BRUNEI DARUSSALAM', code: '' },
        { nationalite: 'BULGARIE', code: '' },
        { nationalite: 'BURKINA-FASO', code: '' },
        { nationalite: 'BURUNDI', code: '' },
        { nationalite: 'CAMBODGE', code: '' },
        { nationalite: 'CAMEROUN', code: '' },
        { nationalite: 'CANADA', code: '' },
        { nationalite: 'CANADA-QUEBEC', code: '' },
        { nationalite: 'CAP-VERT', code: '' },
        { nationalite: 'CAYMAN (Iles)', code: '' },
        { nationalite: 'CENTRAFRICAINE (République)', code: '' },
        { nationalite: 'CHILI', code: '' },
        { nationalite: 'CHINE', code: '' },
        { nationalite: 'CHYPRE', code: '' },
        { nationalite: 'COLOMBIE', code: '' },
        { nationalite: 'COMORES', code: '' },
        { nationalite: 'CONGO', code: '' },
        { nationalite: 'CONGO (Rép. Démocratique)', code: '' },
        { nationalite: 'COOK (Iles)', code: '' },
        { nationalite: 'CORÉE (Rép. Populaire Démocratique)', code: '' },
        { nationalite: 'CORÉE (République de)', code: '' },
        { nationalite: 'COSTA RICA', code: '' },
        { nationalite: 'COTE D\'IVOIRE', code: '' },
        { nationalite: 'CROATIE', code: '' },
        { nationalite: 'CUBA', code: '' },
        { nationalite: 'DANEMARK', code: '' },
        { nationalite: 'DJIBOUTI', code: '' },
        { nationalite: 'DOMINICAINE (République)', code: '' },
        { nationalite: 'DOMINIQUE', code: '' },
        { nationalite: 'EGYPTE', code: '' },
        { nationalite: 'EL SALVADOR', code: '' },
        { nationalite: 'EMIRATS ARABES UNIS', code: '' },
        { nationalite: 'EQUATEUR', code: '' },
        { nationalite: 'ERYTHREE', code: '' },
        { nationalite: 'ESPAGNE', code: '' },
        { nationalite: 'ESTONIE', code: '' },
        { nationalite: 'ETATS-UNIS', code: '' },
        { nationalite: 'ETHIOPIE', code: '' },
        { nationalite: 'FALKLAND (Iles)', code: '' },
        { nationalite: 'FEROE (Iles)', code: '' },
        { nationalite: 'FIDJI', code: '' },
        { nationalite: 'FINLANDE', code: '' },
        { nationalite: 'FRANCE', code: '' },
        { nationalite: 'GABON', code: '' },
        { nationalite: 'GAMBIE', code: '' },
        { nationalite: 'GEORGIE', code: '' },
        { nationalite: 'GHANA', code: '' },
        { nationalite: 'GIBRALTAR', code: '' },
        { nationalite: 'GRECE', code: '' },
        { nationalite: 'GRENADE', code: '' },
        { nationalite: 'GROENLAND', code: '' },
        { nationalite: 'GUADELOUPE', code: '' },
        { nationalite: 'GUAM', code: '' },
        { nationalite: 'GUATEMALA', code: '' },
        { nationalite: 'GUINEE', code: '' },
        { nationalite: 'GUINEE EQUATORIALE', code: '' },
        { nationalite: 'GUINEE-BISSAO', code: '' },
        { nationalite: 'GUYANA', code: '' },
        { nationalite: 'GUYANE FRANCAISE', code: '' },
        { nationalite: 'HAÏTI', code: '' },
        { nationalite: 'HONDURAS', code: '' },
        { nationalite: 'HONG-KONG', code: '' },
        { nationalite: 'HONGRIE', code: '' },
        { nationalite: 'ILES VIERGES AMERICAINES', code: '' },
        { nationalite: 'ILES VIERGES BRITANNIQUES', code: '' },
        { nationalite: 'INDE', code: '' },
        { nationalite: 'INDONESIE', code: '' },
        { nationalite: 'IRAK', code: '' },
        { nationalite: 'IRAN', code: '' },
        { nationalite: 'IRLANDE', code: '' },
        { nationalite: 'ISLANDE', code: '' },
        { nationalite: 'ISRAËL', code: '' },
        { nationalite: 'ITALIE', code: '' },
        { nationalite: 'JAMAÏQUE', code: '' },
        { nationalite: 'JAPON', code: '' },
        { nationalite: 'JERUSALEM', code: '' },
        { nationalite: 'JORDANIE', code: '' },
        { nationalite: 'KAZAKHSTAN', code: '' },
        { nationalite: 'KENYA', code: '' },
        { nationalite: 'KIRGHIZISTAN', code: '' },
        { nationalite: 'KIRIBATI', code: '' },
        { nationalite: 'KOSOVO', code: '' },
        { nationalite: 'KOWEÏT', code: '' },
        { nationalite: 'LAOS', code: '' },
        { nationalite: 'LESOTHO', code: '' },
        { nationalite: 'LETTONIE', code: '' },
        { nationalite: 'LIBAN', code: '' },
        { nationalite: 'LIBERIA', code: '' },
        { nationalite: 'LIBYE', code: '' },
        { nationalite: 'LIECHTENSTEIN', code: '' },
        { nationalite: 'LITUANIE', code: '' },
        { nationalite: 'LUXEMBOURG', code: '' },
        { nationalite: 'MACAO', code: '' },
        { nationalite: 'MACEDOINE', code: '' },
        { nationalite: 'MADAGASCAR', code: '' },
        { nationalite: 'MALAISIE', code: '' },
        { nationalite: 'MALAWI', code: '' },
        { nationalite: 'MALDIVES (Iles)', code: '' },
        { nationalite: 'MALI', code: '' },
        { nationalite: 'MALTE', code: '' },
        { nationalite: 'MARIANNES (Iles)', code: '' },
        { nationalite: 'MAROC', code: '' },
        { nationalite: 'MARSHALL (Iles)', code: '' },
        { nationalite: 'MARTINIQUE', code: '' },
        { nationalite: 'MAURICE', code: '' },
        { nationalite: 'MAURITANIE', code: '' },
        { nationalite: 'MAYOTTE', code: '' },
        { nationalite: 'MEXIQUE', code: '' },
        { nationalite: 'MICRONESIE', code: '' },
        { nationalite: 'MOLDAVIE', code: '' },
        { nationalite: 'MONACO', code: '' },
        { nationalite: 'MONGOLIE', code: '' },
        { nationalite: 'MONTENEGRO', code: '' },
        { nationalite: 'MONTSERRAT', code: '' },
        { nationalite: 'MOZAMBIQUE', code: '' },
        { nationalite: 'NAMIBIE', code: '' },
        { nationalite: 'NAURU', code: '' },
        { nationalite: 'NEPAL', code: '' },
        { nationalite: 'NICARAGUA', code: '' },
        { nationalite: 'NIGER', code: '' },
        { nationalite: 'NIGERIA', code: '' },
        { nationalite: 'NIUE', code: '' },
        { nationalite: 'NORFOLK (Ile)', code: '' },
        { nationalite: 'NORVEGE', code: '' },
        { nationalite: 'NOUVELLE CALEDONIE', code: '' },
        { nationalite: 'NOUVELLE-ZELANDE', code: '' },
        { nationalite: 'OMAN', code: '' },
        { nationalite: 'OUGANDA', code: '' },
        { nationalite: 'OUZBEKISTAN', code: '' },
        { nationalite: 'PAKISTAN', code: '' },
        { nationalite: 'PALAOS', code: '' },
        { nationalite: 'PANAMA', code: '' },
        { nationalite: 'PAPOUASIE-NOUVELLE-GUINEE', code: '' },
        { nationalite: 'PARAGUAY', code: '' },
        { nationalite: 'PAYS-BAS', code: '' },
        { nationalite: 'PEROU', code: '' },
        { nationalite: 'PHILIPPINES', code: '' },
        { nationalite: 'POLOGNE', code: '' },
        { nationalite: 'POLYNESIE FRANCAISE', code: '' },
        { nationalite: 'PORTO RICO, USA', code: '' },
        { nationalite: 'PORTUGAL', code: '' },
        { nationalite: 'QATAR', code: '' },
        { nationalite: 'REUNION', code: '' },
        { nationalite: 'ROUMANIE', code: '' },
        { nationalite: 'ROYAUME-UNI', code: '' },
        { nationalite: 'RUSSIE', code: '' },
        { nationalite: 'RWANDA', code: '' },
        { nationalite: 'SAINTE-HELENE', code: '' },
        { nationalite: 'SAINTE-LUCIE', code: '' },
        { nationalite: 'SAINT-KITTS-ET-NEVIS', code: '' },
        { nationalite: 'SAINT-MARIN', code: '' },
        { nationalite: 'SAINT-PIERRE-ET-MIQUELON', code: '' },
        { nationalite: 'SAINT-VINCENT-ET-LES-GRENADINES', code: '' },
        { nationalite: 'SALOMON (Iles)', code: '' },
        { nationalite: 'SAMOA AMERICAINES', code: '' },
        { nationalite: 'SAMOA OCCIDENTALES', code: '' },
        { nationalite: 'SAO TOME ET PRINCIPE', code: '' },
        { nationalite: 'SENEGAL', code: '' },
        { nationalite: 'SERBIE', code: '' },
        { nationalite: 'SERBIE ET MONTENEGRO', code: '' },
        { nationalite: 'SEYCHELLES', code: '' },
        { nationalite: 'SIERRA LEONE', code: '' },
        { nationalite: 'SINGAPOUR', code: '' },
        { nationalite: 'SLOVAQUIE', code: '' },
        { nationalite: 'SLOVENIE', code: '' },
        { nationalite: 'SOMALIE', code: '' },
        { nationalite: 'SOUDAN', code: '' },
        { nationalite: 'SOUDAN DU SUD', code: '' },
        { nationalite: 'SRI LANKA', code: '' },
        { nationalite: 'SUEDE', code: '' },
        { nationalite: 'SUISSE', code: '' },
        { nationalite: 'SURINAME', code: '' },
        { nationalite: 'SWAZILAND', code: '' },
        { nationalite: 'SYRIE', code: '' },
        { nationalite: 'TADJIKISTAN', code: '' },
        { nationalite: 'TAIWAN', code: '' },
        { nationalite: 'TANZANIE', code: '' },
        { nationalite: 'TCHAD', code: '' },
        { nationalite: 'TCHEQUE (République)', code: '' },
        { nationalite: 'TERRITOIRES PALESTINIENS', code: '' },
        { nationalite: 'THAÏLANDE', code: '' },
        { nationalite: 'TIMOR ORIENTAL', code: '' },
        { nationalite: 'TOGO', code: '' },
        { nationalite: 'TOKELAU', code: '' },
        { nationalite: 'TONGA (Iles)', code: '' },
        { nationalite: 'TRINITE-ET-TOBAGO', code: '' },
        { nationalite: 'TUNISIE', code: '' },
        { nationalite: 'TURKMENISTAN', code: '' },
        { nationalite: 'TURKS ET CAICOS', code: '' },
        { nationalite: 'TURQUIE', code: '' },
        { nationalite: 'TUVALU', code: '' },
        { nationalite: 'UKRAINE', code: '' },
        { nationalite: 'URUGUAY', code: 'URUGUAY', },
        { nationalite: 'VANUATU', code: 'VANUATU', },
        { nationalite: 'VENEZUELA', code: 'VENEZUELA' },
        { nationalite: 'VIETNAM', code: 'VIETNAM', },
        { nationalite: 'WALLIS-ET-FUTUNA', code: 'WALLIS-ET-FUTUNA' },
        { nationalite: 'YEMEN', code: 'YEMEN' },
        { nationalite: 'ZAMBIE', code: 'ZAMBIE', },
        { nationalite: 'ZIMBABWE', code: 'ZIMBABWE' }

    ]

});