Ext.define('zonblewou.store.mesStore.Nationalites', {
    extend: 'Ext.data.Store',

    alias: 'store.nationalites',
    //autoLoad: true,
    /*
    Uncomment to use a specific model class
    model: 'User',
    */

    //model: 'zonblewou.model.mesModeles.Nationalite',

    //Fields can also be declared without a model class:
    fields: ['nationalite', 'code'],

    //Uncomment to specify data inline
    data: [
        { nationalite: 'AFGHANISTAN', code: 'AFGHANISTAN' },
        { nationalite: 'AFRIQUE DU SUD', code: 'AFRIQUE DU SUD' },
        { nationalite: 'ALBANIE', code: 'ALBANIE' },
        { nationalite: 'ALGERIE', code: 'ALGERIE' },
        { nationalite: 'ALLEMAGNE', code: 'ALLEMAGNE' },
        { nationalite: 'ANDORRE', code: 'ANDORRE' },
        { nationalite: 'ANGOLA', code: 'ANGOLA' },
        { nationalite: 'ANGUILLA', code: 'ANGUILLA' },
        { nationalite: 'ANTIGUA-ET-BARBUDA', code: 'ANTIGUA-ET-BARBUDA' },
        { nationalite: 'ANTILLES NEERLANDAISES', code: 'ANTILLES NEERLANDAISES' },
        { nationalite: 'ARABIE SAOUDITE', code: 'ARABIE SAOUDITE' },
        { nationalite: 'ARGENTINE', code: 'ARGENTINE' },
        { nationalite: 'ARMENIE', code: 'ARMENIE' },
        { nationalite: 'ARUBA', code: 'ARUBA' },
        { nationalite: 'ASCENSION', code: 'ASCENSION' },
        { nationalite: 'AUSTRALIE', code: 'AUSTRALIE' },
        { nationalite: 'AUTRICHE', code: 'AUTRICHE' },
        { nationalite: 'AZERBAÏDJAN', code: 'AZERBAÏDJAN' },
        { nationalite: 'BAHAMAS', code: 'BAHAMAS' },
        { nationalite: 'BAHREÏN', code: 'BAHREÏN' },
        { nationalite: 'BANGLADESH', code: 'BANGLADESH' },
        { nationalite: 'BARBADE', code: 'BARBADE' },
        { nationalite: 'BELGIQUE', code: 'BELGIQUE' },
        { nationalite: 'BELIZE', code: 'BELIZE' },
        { nationalite: 'BENIN', code: 'BENIN' },
        { nationalite: 'BERMUDES', code: 'BERMUDES' },
        { nationalite: 'BHOUTAN', code: 'BHOUTAN' },
        { nationalite: 'BIELORUSSIE', code: 'BIELORUSSIE' },
        { nationalite: 'BIRMANIE', code: 'BIRMANIE' },
        { nationalite: 'BOLIVIE', code: 'BOLIVIE' },
        { nationalite: 'BOSNIE-HERZEGOVINE', code: 'BOSNIE-HERZEGOVINE' },
        { nationalite: 'BOTSWANA', code: 'BOTSWANA' },
        { nationalite: 'BRESIL', code: 'BRESIL' },
        { nationalite: 'BRUNEI DARUSSALAM', code: 'BRUNEI DARUSSALAM' },
        { nationalite: 'BULGARIE', code: 'BULGARIE' },
        { nationalite: 'BURKINA-FASO', code: 'BURKINA-FASO' },
        { nationalite: 'BURUNDI', code: 'BURUNDI' },
        { nationalite: 'CAMBODGE', code: 'CAMBODGE' },
        { nationalite: 'CAMEROUN', code: 'CAMEROUN' },
        { nationalite: 'CANADA', code: 'CANADA' },
        { nationalite: 'CANADA-QUEBEC', code: 'CANADA-QUEBEC' },
        { nationalite: 'CAP-VERT', code: 'CAP-VERT' },
        { nationalite: 'CAYMAN (Iles)', code: 'CAYMAN (Iles)' },
        { nationalite: 'CENTRAFRICAINE (République)', code: 'CENTRAFRICAINE (République)' },
        { nationalite: 'CHILI', code: 'CHILI' },
        { nationalite: 'CHINE', code: 'CHINE' },
        { nationalite: 'CHYPRE', code: 'CHYPRE' },
        { nationalite: 'COLOMBIE', code: 'COLOMBIE' },
        { nationalite: 'COMORES', code: 'COMORES' },
        { nationalite: 'CONGO', code: 'CONGO' },
        { nationalite: 'CONGO (Rép. Démocratique)', code: 'CONGO (Rép. Démocratique)' },
        { nationalite: 'COOK (Iles)', code: 'COOK (Iles)' },
        { nationalite: 'CORÉE (Rép. Populaire Démocratique)', code: 'CORÉE (Rép. Populaire Démocratique)' },
        { nationalite: 'CORÉE (République de)', code: 'CORÉE (République de)' },
        { nationalite: 'COSTA RICA', code: 'COSTA RICA' },
        { nationalite: 'COTE D\'IVOIRE', code: 'COTE D\'IVOIRE' },
        { nationalite: 'CROATIE', code: 'CROATIE' },
        { nationalite: 'CUBA', code: 'CUBA' },
        { nationalite: 'DANEMARK', code: 'DANEMARK' },
        { nationalite: 'DJIBOUTI', code: 'DJIBOUTI' },
        { nationalite: 'DOMINICAINE (République)', code: 'DOMINICAINE (République)' },
        { nationalite: 'DOMINIQUE', code: 'DOMINIQUE' },
        { nationalite: 'EGYPTE', code: 'EGYPTE' },
        { nationalite: 'EL SALVADOR', code: 'EL SALVADOR' },
        { nationalite: 'EMIRATS ARABES UNIS', code: 'EMIRATS ARABES UNIS' },
        { nationalite: 'EQUATEUR', code: 'EQUATEUR' },
        { nationalite: 'ERYTHREE', code: 'ERYTHREE' },
        { nationalite: 'ESPAGNE', code: 'ESPAGNE' },
        { nationalite: 'ESTONIE', code: 'ESTONIE' },
        { nationalite: 'ETATS-UNIS', code: 'ETATS-UNIS' },
        { nationalite: 'ETHIOPIE', code: 'ETHIOPIE' },
        { nationalite: 'FALKLAND (Iles)', code: 'FALKLAND' },
        { nationalite: 'FEROE (Iles)', code: 'FEROE (Iles)' },
        { nationalite: 'FIDJI', code: 'FIDJI' },
        { nationalite: 'FINLANDE', code: 'FINLANDE' },
        { nationalite: 'FRANCE', code: 'FRANCE' },
        { nationalite: 'GABON', code: 'GABON' },
        { nationalite: 'GAMBIE', code: 'GAMBIE' },
        { nationalite: 'GEORGIE', code: 'GEORGIE' },
        { nationalite: 'GHANA', code: 'GHANA' },
        { nationalite: 'GIBRALTAR', code: 'GIBRALTAR' },
        { nationalite: 'GRECE', code: 'GRECE' },
        { nationalite: 'GRENADE', code: 'GRENADE' },
        { nationalite: 'GROENLAND', code: 'GROENLAND' },
        { nationalite: 'GUADELOUPE', code: 'GUADELOUPE' },
        { nationalite: 'GUAM', code: 'GUAM' },
        { nationalite: 'GUATEMALA', code: 'GUATEMALA' },
        { nationalite: 'GUINEE', code: 'GUINEE' },
        { nationalite: 'GUINEE EQUATORIALE', code: 'GUINEE EQUATORIALE' },
        { nationalite: 'GUINEE-BISSAO', code: 'UINEE-BISSAO' },
        { nationalite: 'GUYANA', code: 'GUYANA' },
        { nationalite: 'GUYANE FRANCAISE', code: 'GUYANE FRANCAISE' },
        { nationalite: 'HAÏTI', code: 'HAÏTI' },
        { nationalite: 'HONDURAS', code: 'HONDURAS' },
        { nationalite: 'HONG-KONG', code: 'HONG-KONG' },
        { nationalite: 'HONGRIE', code: 'HONGRIE' },
        { nationalite: 'ILES VIERGES AMERICAINES', code: 'ILES VIERGES AMERICAINES' },
        { nationalite: 'ILES VIERGES BRITANNIQUES', code: 'ILES VIERGES BRITANNIQUES' },
        { nationalite: 'INDE', code: 'INDE' },
        { nationalite: 'INDONESIE', code: 'INDONESIE' },
        { nationalite: 'IRAK', code: 'IRAK' },
        { nationalite: 'IRAN', code: 'IRAN' },
        { nationalite: 'IRLANDE', code: 'IRLANDE' },
        { nationalite: 'ISLANDE', code: 'ISLANDE' },
        { nationalite: 'ISRAËL', code: 'ISRAËL' },
        { nationalite: 'ITALIE', code: 'ITALIE' },
        { nationalite: 'JAMAÏQUE', code: 'JAMAÏQUE' },
        { nationalite: 'JAPON', code: 'JAPON' },
        { nationalite: 'JERUSALEM', code: 'JERUSALEM' },
        { nationalite: 'JORDANIE', code: 'JORDANIE' },
        { nationalite: 'KAZAKHSTAN', code: 'KAZAKHSTAN' },
        { nationalite: 'KENYA', code: 'KENYA' },
        { nationalite: 'KIRGHIZISTAN', code: 'KIRGHIZISTAN' },
        { nationalite: 'KIRIBATI', code: 'KIRIBATI' },
        { nationalite: 'KOSOVO', code: 'KOSOVO' },
        { nationalite: 'KOWEÏT', code: 'KOWEÏT' },
        { nationalite: 'LAOS', code: 'LAOS' },
        { nationalite: 'LESOTHO', code: 'LESOTHO' },
        { nationalite: 'LETTONIE', code: 'LETTONIE' },
        { nationalite: 'LIBAN', code: 'LIBAN' },
        { nationalite: 'LIBERIA', code: 'LIBERIA' },
        { nationalite: 'LIBYE', code: 'LIBYE' },
        { nationalite: 'LIECHTENSTEIN', code: 'LIECHTENSTEIN' },
        { nationalite: 'LITUANIE', code: 'LITUANIE' },
        { nationalite: 'LUXEMBOURG', code: 'LUXEMBOURG' },
        { nationalite: 'MACAO', code: 'MACAO' },
        { nationalite: 'MACEDOINE', code: 'MACEDOINE' },
        { nationalite: 'MADAGASCAR', code: 'MADAGASCAR' },
        { nationalite: 'MALAISIE', code: 'MALAISIE' },
        { nationalite: 'MALAWI', code: 'MALAWI' },
        { nationalite: 'MALDIVES (Iles)', code: 'MALDIVES' },
        { nationalite: 'MALI', code: 'MALI' },
        { nationalite: 'MALTE', code: 'MALTE' },
        { nationalite: 'MARIANNES (Iles)', code: 'MARIANNES' },
        { nationalite: 'MAROC', code: 'MAROC' },
        { nationalite: 'MARSHALL (Iles)', code: 'MARSHALL (Iles)' },
        { nationalite: 'MARTINIQUE', code: 'MARTINIQUE' },
        { nationalite: 'MAURICE', code: 'MAURICE' },
        { nationalite: 'MAURITANIE', code: 'MAURITANIE' },
        { nationalite: 'MAYOTTE', code: 'MAYOTTE' },
        { nationalite: 'MEXIQUE', code: 'MEXIQUE' },
        { nationalite: 'MICRONESIE', code: 'MICRONESIE' },
        { nationalite: 'MOLDAVIE', code: 'MOLDAVIE' },
        { nationalite: 'MONACO', code: 'MONACO' },
        { nationalite: 'MONGOLIE', code: 'MONGOLIE' },
        { nationalite: 'MONTENEGRO', code: 'MONTENEGRO' },
        { nationalite: 'MONTSERRAT', code: 'MONTSERRAT' },
        { nationalite: 'MOZAMBIQUE', code: 'MOZAMBIQUE' },
        { nationalite: 'NAMIBIE', code: 'NAMIBIE' },
        { nationalite: 'NAURU', code: 'NAURU' },
        { nationalite: 'NEPAL', code: 'NEPAL' },
        { nationalite: 'NICARAGUA', code: 'NICARAGUA' },
        { nationalite: 'NIGER', code: 'NIGER' },
        { nationalite: 'NIGERIA', code: 'NIGERIA' },
        { nationalite: 'NIUE', code: 'NIUE' },
        { nationalite: 'NORFOLK (Ile)', code: 'NORFOLK (Ile)' },
        { nationalite: 'NORVEGE', code: 'NORVEGE' },
        { nationalite: 'NOUVELLE CALEDONIE', code: 'NOUVELLE CALEDONIE' },
        { nationalite: 'NOUVELLE-ZELANDE', code: 'NOUVELLE-ZELANDE' },
        { nationalite: 'OMAN', code: 'OMAN' },
        { nationalite: 'OUGANDA', code: 'OUGANDA' },
        { nationalite: 'OUZBEKISTAN', code: 'OUZBEKISTAN' },
        { nationalite: 'PAKISTAN', code: 'PAKISTAN' },
        { nationalite: 'PALAOS', code: 'PALAOS' },
        { nationalite: 'PANAMA', code: 'PANAMA' },
        { nationalite: 'PAPOUASIE-NOUVELLE-GUINEE', code: 'PAPOUASIE-NOUVELLE-GUINEE' },
        { nationalite: 'PARAGUAY', code: 'PARAGUAY' },
        { nationalite: 'PAYS-BAS', code: 'PAYS-BAS' },
        { nationalite: 'PEROU', code: 'PEROU' },
        { nationalite: 'PHILIPPINES', code: 'PHILIPPINES' },
        { nationalite: 'POLOGNE', code: 'POLOGNE' },
        { nationalite: 'POLYNESIE FRANCAISE', code: 'POLYNESIE FRANCAISE' },
        { nationalite: 'PORTO RICO, USA', code: 'PORTO RICO, USA' },
        { nationalite: 'PORTUGAL', code: 'PORTUGAL' },
        { nationalite: 'QATAR', code: 'QATAR' },
        { nationalite: 'REUNION', code: 'REUNION' },
        { nationalite: 'ROUMANIE', code: 'ROUMANIE' },
        { nationalite: 'ROYAUME-UNI', code: 'ROYAUME-UNI' },
        { nationalite: 'RUSSIE', code: 'RUSSIE' },
        { nationalite: 'RWANDA', code: 'RWANDA' },
        { nationalite: 'SAINTE-HELENE', code: 'SAINTE-HELENE' },
        { nationalite: 'SAINTE-LUCIE', code: 'SAINTE-LUCIE' },
        { nationalite: 'SAINT-KITTS-ET-NEVIS', code: 'SAINT-KITTS-ET-NEVIS' },
        { nationalite: 'SAINT-MARIN', code: 'SAINT-MARIN' },
        { nationalite: 'SAINT-PIERRE-ET-MIQUELON', code: 'SAINT-PIERRE-ET-MIQUELON' },
        { nationalite: 'SAINT-VINCENT-ET-LES-GRENADINES', code: 'SAINT-VINCENT-ET-LES-GRENADINES' },
        { nationalite: 'SALOMON (Iles)', code: 'SALOMON (Iles)' },
        { nationalite: 'SAMOA AMERICAINES', code: 'SAMOA AMERICAINES' },
        { nationalite: 'SAMOA OCCIDENTALES', code: 'SAMOA OCCIDENTALES' },
        { nationalite: 'SAO TOME ET PRINCIPE', code: 'SAO TOME ET PRINCIPE' },
        { nationalite: 'SENEGAL', code: 'SENEGAL' },
        { nationalite: 'SERBIE', code: 'SERBIE' },
        { nationalite: 'SERBIE ET MONTENEGRO', code: 'SERBIE ET MONTENEGRO' },
        { nationalite: 'SEYCHELLES', code: 'SEYCHELLES' },
        { nationalite: 'SIERRA LEONE', code: 'SIERRA LEONE' },
        { nationalite: 'SINGAPOUR', code: 'SINGAPOUR' },
        { nationalite: 'SLOVAQUIE', code: 'SLOVAQUIE' },
        { nationalite: 'SLOVENIE', code: 'SLOVENIE' },
        { nationalite: 'SOMALIE', code: 'SOMALIE' },
        { nationalite: 'SOUDAN', code: 'SOUDAN' },
        { nationalite: 'SOUDAN DU SUD', code: 'SOUDAN DU SUD' },
        { nationalite: 'SRI LANKA', code: 'SRI LANKA' },
        { nationalite: 'SUEDE', code: 'SUEDE' },
        { nationalite: 'SUISSE', code: 'SUISSE' },
        { nationalite: 'SURINAME', code: 'SURINAME' },
        { nationalite: 'SWAZILAND', code: 'SWAZILAND' },
        { nationalite: 'SYRIE', code: 'SYRIE' },
        { nationalite: 'TADJIKISTAN', code: 'TADJIKISTAN' },
        { nationalite: 'TAIWAN', code: 'TAIWAN' },
        { nationalite: 'TANZANIE', code: 'TANZANIE' },
        { nationalite: 'TCHAD', code: 'TCHAD' },
        { nationalite: 'TCHEQUE (République)', code: 'TCHEQUE (République)' },
        { nationalite: 'TERRITOIRES PALESTINIENS', code: 'TERRITOIRES PALESTINIENS' },
        { nationalite: 'THAÏLANDE', code: 'THAÏLANDE' },
        { nationalite: 'TIMOR ORIENTAL', code: 'TIMOR ORIENTAL' },
        { nationalite: 'TOGO', code: 'TOGO' },
        { nationalite: 'TOKELAU', code: 'TOKELAU' },
        { nationalite: 'TONGA (Iles)', code: 'TONGA (Iles)' },
        { nationalite: 'TRINITE-ET-TOBAGO', code: 'TRINITE-ET-TOBAGO' },
        { nationalite: 'TUNISIE', code: 'TUNISIE' },
        { nationalite: 'TURKMENISTAN', code: 'TURKMENISTAN' },
        { nationalite: 'TURKS ET CAICOS', code: 'TURKS ET CAICOS' },
        { nationalite: 'TURQUIE', code: 'TURQUIE' },
        { nationalite: 'TUVALU', code: 'TUVALU' },
        { nationalite: 'UKRAINE', code: 'UKRAINE' },
        { nationalite: 'URUGUAY', code: 'URUGUAY', },
        { nationalite: 'VANUATU', code: 'VANUATU', },
        { nationalite: 'VENEZUELA', code: 'VENEZUELA' },
        { nationalite: 'VIETNAM', code: 'VIETNAM', },
        { nationalite: 'WALLIS-ET-FUTUNA', code: 'WALLIS-ET-FUTUNA' },
        { nationalite: 'YEMEN', code: 'YEMEN' },
        { nationalite: 'ZAMBIE', code: 'ZAMBIE', },
        { nationalite: 'ZIMBABWE', code: 'ZIMBABWE' }

    ]

});