---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msmega-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podlabel
  template:
    metadata:
      labels:
        app: podlabel
    spec:
      containers:
        - name: msmega:${BUILD_ID}
          image: msmegaappimage:${BUILD_ID}
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: msmega-service
spec:
  selector:
    app: podlabel
  ports:
    - port: 8088
      targetPort: 8081
  type: LoadBalancer
