<?php

namespace Prov\BackBundle\Repository;

/**
 * ConditionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionnementRepository extends \Doctrine\ORM\EntityRepository
{
}
