<?php

namespace Prov\BackBundle\Repository;

/**
 * TypeMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMaterielRepository extends \Doctrine\ORM\EntityRepository
{
}
