<?php


namespace App\service;


use Illuminate\Support\Facades\DB;

class AgentMarketingService extends GenericService
{
    // Constructeur

    public function __construct()
    {
        parent::__construct();
    }

    public function findAll(string $class)
    {
       // return parent::findAll($class); // TODO: Change the autogenerated stub

        $agMarketing = DB::table('agent_marketings')

            ->join('zones', 'agent_marketings.idZone', '=', 'zones.id')

            ->join('agences', 'agent_marketings.idAgence', '=', 'agences.id')

            ->select('agent_marketings.id as id','nomAg','prenomAg', 'telAg', 'adresseAg', 'zones.id as idZone','zones.zone as zone', 'agences.id as idAgence', 'agences.agence as agence')

            ->get();

        return $agMarketing;
       // return \response()->json( $agMarketing, 200);
    }

}
