<?php


namespace App\service;

use Illuminate\Support\Facades\DB;

use http\Client\Response;
use Illuminate\Http\Request;

use Illuminate\Support\Collection;


class DepotMarketeurService extends GenericService
{
    // Constructeur

    public function __construct()
    {
        parent::__construct();
    }


    public function findAll(string $class)
    {
         //return parent::store($req); // TODO: Change the autogenerated stub

         // requete

        $depotMarketeurListe = DB::table('depot_marketeurs')

        ->join('agent_marketings', 'depot_marketeurs.idAgent', '=', 'agent_marketings.id')

        ->join('compte_de_depots', 'depot_marketeurs.idCptDepot', '=', 'compte_de_depots.id')

        ->select('depot_marketeurs.id as id', 'agent_marketings.id as idAgent', 'compte_de_depots.id as idCompte', 'numCompteDep','dateDepot', 'montantDepot', 'agent_marketings.nomAg as nomAg','agent_marketings.prenomAg as prenomAg')

        ->get();

        return $depotMarketeurListe;
    }

    public function infoCompteDep(int $id)
    {
        $info = DB::table('compte_de_depots')

        ->join('agent_marketings', 'compte_de_depots.idAgent', '=', 'agent_marketings.id')

        ->select('compte_de_depots.id as id','numCompteDep')

        ->where('compte_de_depots.idAgent', '=', $id)

        ->get();

        return $info;


    }

}
